package: activity_log
version: "0.0.1"
name: Activity Log
author: eaCe
supportpage: https://github.com/eace/activity_log

page:
    title: translate:title
    perm: admin
    icon: rex-icon fa-list-alt
    subpages:
        system.activity-log: { title: 'translate:activity_log_title' }
        settings: { title: translate:settings }
        help: { title: translate:help, subPath: README.md, icon: rex-icon fa-question-circle, itemclass: pull-right }

pages:
  system/activity-log:
    title: 'translate:activity_log_title'
    perm: activity_log[]

requires:
  redaxo: ^5.12.0
  php:
    version: '>=7.1'

installer_ignore:
  - node_modules
  - .git
  - .gitignore
  - .github
  - package.json
  - yarn.lock
  - resources
  - .editorconfig
  - .eslintrc.js
  - .stylelintrc.js
