package: activity_log
version: "0.1.0"
name: Activity Log
author: FriendsOfREDAXO
supportpage: https://github.com/FriendsOfREDAXO/activity_log

page:
    title: translate:title
    perm: admin
    icon: rex-icon fa-list-alt
    subpages:
        system.activity-log: { title: 'translate:activity_log_title' }
        settings: { title: translate:settings }
        help: { title: translate:help, subPath: README.md, icon: rex-icon fa-question-circle, itemclass: pull-right }

pages:
  system/activity-log:
    title: 'translate:activity_log_title'
    perm: admin

console_commands:
  activity:clear: activity_clear

requires:
  redaxo: ^5.12.0
  php:
    version: '>=8.0'

default_config:
  'article_added': false
  'article_updated': false
  'article_status': false
  'article_deleted': false
  'category_added': false
  'category_updated': false
  'category_deleted': false
  'category_status': false
  'slice_added': false
  'slice_updated': false
  'slice_deleted': false
  'slice_moved': false
  'meta_updated': false
  'clang_added': false
  'clang_updated': false
  'clang_deleted': false
  'user_added': false
  'user_updated': false
  'user_deleted': false
  'media_added': false
  'media_updated': false
  'media_deleted': false
  'template_added': false
  'template_updated': false
  'template_deleted': false
  'module_added': false
  'module_updated': false
  'module_deleted': false
  'rows_per_page': 100

installer_ignore:
  - .git
  - .github
  - node_modules
  - tests
  - tests_output
  - .editorconfig
  - .eslintrc.js
  - .gitignore
  - .stylelintrc.js
  - composer.json
  - composer.lock
  - nightwatch.conf.js
  - package.json
  - package-lock.json
  - yarn.lock
  - phpcs.xml
  - phpunit.xml
  - resources
  - .php-cs-fixer.dist.php
