name: PHP-CS-Fixer

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

permissions:
  contents: read

jobs:
  cs-fixer:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: gd, intl
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-scripts

      - name: Run PHP CS Fixer
        run: composer cs-dry
